-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: "6b1aa19425b35f8c34f43ada8f1045b028dc19a5"
    hooks:
    # keep ids alphabetical! see http://pre-commit.com/hooks.html
    -   id: debug-statements
        files: \.py$
    -   id: flake8
        files: \.(py|sh)$
    -   id: name-tests-test
        name: Django Tests should start with test_ prefix
        files: tests/.+\.py$
        args: ['--django']  # args: ['--django'] will match test*.py instead.
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
    -   id: python-import-sorter
        args: ['--diff']
