os: linux
dist: xenial

language: python
cache: pip
python:
  - "3.8"

jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      env:
        global:
          - USE_DOCKER="no"
          - DATABASE_URL="postgres:///{{ cookiecutter.project_slug }}"
          {% if cookiecutter.use_celery == 'y' -%}
          - CELERY_BROKER_URL="redis://localhost:6379/0"
          {%- endif %}
      services:
        - postgresql
        {% if cookiecutter.use_celery == 'y' -%}
        - redis
        {%- endif %}
      install:
        - pip install -r requirements/local.txt
      before_script:
        - celery multi start worker beat -A config.celery_app --pool=solo
      script:
        - "pytest"
