version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./Dockerfile
    image: {{ cookiecutter.project_slug }}_django
    depends_on:
      - postgres
      {%- if cookiecutter.use_mailhog == 'y' %}
      - mailhog
      {%- endif %}
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /app/bin/start-django-dev

  postgres:
    image: postgres:11-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env
    ports:
      - "5432:5432"
  {%- if cookiecutter.use_mailhog == 'y' %}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
  {%- endif %}

  redis:
    image: redis:5.0
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_celeryworker
    depends_on:
      - redis
      - postgres
      {% if cookiecutter.use_mailhog == 'y' -%}
      - mailhog
      {%- endif %}
    ports: []
    command: /app/bin/start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_celerybeat
    depends_on:
      - redis
      - postgres
      {% if cookiecutter.use_mailhog == 'y' -%}
      - mailhog
      {%- endif %}
    ports: []
    command: /app/bin/start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_flower
    ports:
      - "5555:5555"
    command: /app/bin/start-flower

  {%- endif %}

  node:
    image: node:10-stretch-slim
    depends_on:
      - django
    volumes:
      - .:/app
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
