version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-test
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    links:
      - postgres
{% if cookiecutter.use_mailhog == 'y' %}
      - mailhog
{% endif %}

{% if cookiecutter.use_mailhog == 'y' %}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
{% endif %}
