# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch: main

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: update

# set a global prefix for PRs
# default: empty
pr_prefix: "Bug #12345"

requirements:
  - "requirements.txt"
  - "docs/requirements.txt"
  - "{{cookiecutter.project_slug}}/requirements/base.txt"
  - "{{cookiecutter.project_slug}}/requirements/local.txt"
  - "{{cookiecutter.project_slug}}/requirements/production.txt"
