name: "Automerge"

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    
    if: github.actor == 'pyup-bot'
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.2.0
        with:
          ignoreActions: automerge,WIP
          checkInterval: 300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Automerge'
        uses: pascalgn/automerge-action@v0.11.0
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_LABELS: "update"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
